// <auto-generated />
using System;
using EventSourcing.Persistence.EntityFramework.Postgres.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventSourcing.Persistence.EntityFramework.Postgres.Migrations
{
    [DbContext(typeof(PostgresEventStoreContext))]
    [Migration("20261009062654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventSourcing.Persistence.EntityFramework.Event", b =>
                {
                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Position");

                    b.HasIndex("StreamType", "StreamId");

                    b.ToTable("Events", "public");
                });

            modelBuilder.Entity("EventSourcing.Persistence.EntityFramework.Postgres.Infrastructure.EventPositionCounter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("LastPosition")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("EventPositionCounter", "public", t =>
                        {
                            t.HasCheckConstraint("CK_EventPositionCounter_SingleRow", "\"Id\" = 1 AND \"LastPosition\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastPosition = 0L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
