using System;

namespace EventSourcing.Commands;

/// <summary>
/// Partial class can be attributed with the CommandExtensions attribute.
/// Useful extensions and command processor base classes for result and failure types are added by the source generator shipped with EventSourcing.Commands.
/// </summary>
/// <typeparam name="TResult">has to implement EventSourcing.Commands.IResult (which is automatically working with result types generated by FunicularSwitch.Generators package)</typeparam>
/// <typeparam name="TFailure">has to implement EventSourcing.Commands.IFailure</typeparam>

[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public class CommandExtensionsAttribute<TResult, TFailure> : Attribute
    where TFailure : IFailure<TFailure>;